---
# configure
- name: Place sshd configuration file.
  template:
    src: sshd_config.rhel-{{ ansible_distribution_major_version }}.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 00600

# service
- name: Ensure sshd is started and enabled to start at boot.
  service: name=sshd state=started enabled=yes
